- name: Install UFW on all hosts
  hosts: all
  become: true
  tasks:
    - name: Install UFW
      ansible.builtin.apt:
        name: ufw
        state: present
        update_cache: true
    - name: UFW - Allow SSH connections
      community.general.ufw:
        rule: allow
        name: OpenSSH
        state: enabled

- name: Open TCP Ports on ControlPlane
  hosts: master
  become: true
  tasks:
    # 6443, 2379-2380, 10250, 10259, 10257 for K8s
    # 179 for Calico BGP, 5473 for Calico Typha
    # 9100 for Prometheus Node Exporter
    - name: UFW - Allow TCP ports 6443, 2379-2380, 10250, 10259, 10257, 179, 5473, 9100
      community.general.ufw:
        rule: allow
        port: "6443,2379:2380,10250,10259,10257,179,5473,9100"
        proto: tcp

- name: Open TCP Ports on Worker Nodes
  hosts: workers
  become: true
  tasks:
    # 10250, 10256, 30000-32767 for K8s
    # 179 for Calico BGP, 5473 for Calico Typha
    # 80 and 443 for Traefik
    # 9100 for Prometheus Node Exporter
    - name: UFW - Allow TCP ports 10250, 10256, 30000-32767, 179, 5473, 80, 443, 9100
      community.general.ufw:
        rule: allow
        port: "10250,10256,30000:32767,179,5473,80,443,9100"
        proto: tcp

- name: Open UDP Ports on Worker Nodes
  hosts: workers
  become: true
  tasks:
    # 30000-32767 for K8s
    - name: UFW - Allow UDP ports 30000-32767
      community.general.ufw:
        rule: allow
        port: "30000:32767"
        proto: udp

- name: Verify UFW Status
  hosts: all
  become: true
  tasks:
    - name: Check UFW status
      ansible.builtin.command: ufw status verbose
      register: ufw_status
      changed_when: false
    - name: Display UFW status
      ansible.builtin.debug:
        var: ufw_status.stdout_lines
