- name: Ensure required kernel modules and sysctl settings for Kubernetes
  hosts: all
  become: true
  tasks:
    - name: Load overlay kernel module
      community.general.modprobe:
        name: overlay
        state: present
      changed_when: false

    - name: Load br_netfilter kernel module
      community.general.modprobe:
        name: br_netfilter
        state: present
      changed_when: false

    - name: Persist kernel modules
      ansible.builtin.copy:
        content: |
          overlay
          br_netfilter
        dest: /etc/modules-load.d/k8s.conf
        mode: '0644'

    - name: Configure sysctl for Kubernetes
      ansible.builtin.copy:
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1
        dest: /etc/sysctl.d/k8s.conf
        mode: '0644'

    - name: Apply sysctl settings
      ansible.builtin.command: sudo sysctl --system
      changed_when: false

    - name: Restart kubelet
      ansible.builtin.service:
        name: kubelet
        state: restarted

    - name: Restart containerd
      ansible.builtin.service:
        name: containerd
        state: restarted
