- name: Initialize Kubernetes Cluster
  hosts: all
  become: true

  vars:
    control_plane_endpoint: "192.168.4.35"
    pod_network_cidr: "10.244.0.0/16"
    calico_version: "v3.31.4"

  tasks:
    - name: Set hostnames
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

    - name: Ensure all nodes are resolvable in /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ hostvars[item].ansible_default_ipv4.address }} {{ item }}"
        state: present
      loop: "{{ groups['all'] }}"

    - name: Reset kubeadm
      changed_when: false
      ansible.builtin.command: kubeadm reset -f

    - name: Remove CNI directories if cluster exists
      ansible.builtin.file:
        path: /etc/cni/net.d
        state: absent

    - name: Restart kubelet
      ansible.builtin.service:
        name: kubelet
        state: restarted

    - name: Ensure containerd config directory exists
      ansible.builtin.file:
        path: /etc/containerd
        state: directory
        mode: '0755'

    - name: Generate default containerd config
      changed_when: false
      ansible.builtin.command: containerd config default
      register: containerd_default_config

    - name: Write containerd config to /etc/containerd/config.toml
      ansible.builtin.copy:
        content: "{{ containerd_default_config.stdout }}"
        dest: /etc/containerd/config.toml
        owner: root
        group: root
        mode: '0644'
        force: true

    - name: Set SystemdCgroup to true
      ansible.builtin.replace:
        path: /etc/containerd/config.toml
        regexp: 'SystemdCgroup = false'
        replace: 'SystemdCgroup = true'

    - name: Replace CNI bin_dir path
      ansible.builtin.replace:
        path: /etc/containerd/config.toml
        regexp: 'bin_dir = "/usr/lib/cni"'
        replace: 'bin_dir = "/opt/cni/bin"'

    - name: Set correct sandbox image
      ansible.builtin.replace:
        path: /etc/containerd/config.toml
        regexp: 'sandbox_image = ".*"'
        replace: 'sandbox_image = "registry.k8s.io/pause:3.10.1"'

    - name: Restart containerd
      changed_when: false
      ansible.builtin.service:
        name: containerd
        state: restarted

    - name: Initialize Kubernetes cluster with kubeadm
      when: "'master' in group_names"
      ansible.builtin.shell: >
        kubeadm init
        --pod-network-cidr="{{ pod_network_cidr }}"
        --apiserver-advertise-address="{{ control_plane_endpoint }}"
      args:
        creates: "/etc/kubernetes/admin.conf"

    - name: Generate kubeadm join command
      when: "'master' in group_names"
      changed_when: false
      ansible.builtin.shell: |
        kubeadm token create --print-join-command
      register: join_command
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

    - name: Print worker join command
      when: "'master' in group_names"
      ansible.builtin.debug:
        var: join_command

    - name: Copy kubeconfig to control node (dev machine)
      when: "'master' in group_names"
      ansible.builtin.fetch:
        src: /etc/kubernetes/admin.conf
        dest: ~/.kube/homelab_kubeconfig.yaml
        flat: true

    - name: Install the Tigera Operator and custom resource definitions
      when: "'master' in group_names"
      changed_when: false
      ansible.builtin.shell: >
        kubectl apply -f
        https://raw.githubusercontent.com/projectcalico/calico/{{ calico_version }}/manifests/tigera-operator.yaml
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

    - name: Wait for Installation CRD to be registered
      ansible.builtin.shell: >
        kubectl get crd installations.operator.tigera.io
      when: "'master' in group_names"
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      register: crd_check
      retries: 20
      delay: 15
      until: crd_check.rc == 0
      changed_when: false

    - name: Install Calico CNI
      when: "'master' in group_names"
      changed_when: false
      ansible.builtin.shell: >
        kubectl apply -f
        https://raw.githubusercontent.com/projectcalico/calico/{{ calico_version }}/manifests/custom-resources.yaml
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

    # Default Calico installation uses 192.168.0.0/16 CIDR for pods
    # This conflicts with node IPs on my home network (192.168.x.x)
    # We must patch the Calico installation to use the correct CIDR for the pod network
    - name: Patch Calico Installation CIDR with POD Network CIDR
      when: "'master' in group_names"
      changed_when: "'patched' in calico_patch.stdout"
      ansible.builtin.shell: |
        kubectl patch installation default \
          --type merge \
          -p '{
            "spec": {
              "calicoNetwork": {
                "ipPools": [
                  {
                    "name": "default-ipv4-ippool",
                    "cidr": "{{ pod_network_cidr }}",
                    "blockSize": 26,
                    "encapsulation": "VXLANCrossSubnet",
                    "natOutgoing": "Enabled",
                    "nodeSelector": "all()",
                    "disableBGPExport": false
                  }
                ]
              }
            }
          }'
      register: calico_patch
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

    - name: Join worker nodes
      when: "'workers' in group_names"
      ansible.builtin.shell: >
        {{ hostvars[groups['master'][0]].join_command.stdout }}
      args:
        creates: /etc/kubernetes/kubelet.conf
